site_name: Geospatial Notebooks

site_url: https://notebooks.gishub.org

repo_url: https://github.com/giswqs/geospatial-notebooks

theme:
  palette:
    scheme: preference
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    # - navigation.expand
    # - navigation.tabs
    - search.highlight
  custom_dir: "docs/overrides"

plugins:
  - search
  - mkdocstrings
  - git-revision-date
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
      execute: True

markdown_extensions:
  - attr_list
  - toc:
      permalink: true

# google_analytics:
#   - UA-XXXXXXXX-X
#   - auto

nav:
  - Home: index.ipynb'
  - Geemap:
      - geemap/00_geemap_key_features.ipynb
      - geemap/01_geemap_intro.ipynb
      - geemap/02_using_basemaps.ipynb
      - geemap/03_inspector_tool.ipynb
      - geemap/04_split_panel_map.ipynb
      - geemap/05_drawing_tools.ipynb
      - geemap/06_marker_cluster.ipynb
      - geemap/07_geojson.ipynb
      - geemap/08_ee_js_to_ipynb.ipynb
      - geemap/09_plotting.ipynb
      - geemap/10_shapefiles.ipynb
      - geemap/11_export_image.ipynb
      - geemap/12_zonal_statistics.ipynb
      - geemap/13_zonal_statistics_by_group.ipynb
      - geemap/14_legends.ipynb
      - geemap/15_convert_js_to_py.ipynb
      - geemap/16_add_animated_text.ipynb
      - geemap/17_add_colorbar_to_gif.ipynb
      - geemap/18_create_landsat_timelapse.ipynb
      - geemap/19_search_places_and_datasets.ipynb
      - geemap/20_timeseries_inspector.ipynb
      - geemap/21_export_map_to_html_png.ipynb
      - geemap/22_import_scripts.ipynb
      - geemap/23_import_assets.ipynb
      - geemap/24_publish_maps.ipynb
      - geemap/25_load_rasters.ipynb
      - geemap/26_heroku.ipynb
      - geemap/27_timelapse_app.ipynb
      - geemap/28_voila.ipynb
      - geemap/29_pydeck.ipynb
      - geemap/30_image_props_stats.ipynb
      - geemap/31_unsupervised_classification.ipynb
      - geemap/32_supervised_classification.ipynb
      - geemap/33_accuracy_assessment.ipynb
      - geemap/34_extract_values.ipynb
      - geemap/35_geemap_colab.ipynb
      - geemap/36_quality_mosaic.ipynb
      - geemap/37_pydeck_3d.ipynb
      - geemap/38_cloud_geotiff.ipynb
      - geemap/39_timelapse.ipynb
      - geemap/40_ipywidgets.ipynb
      - geemap/41_water_app.ipynb
      - geemap/42_upload_data.ipynb
      - geemap/43_extract_values_to_points.ipynb
      - geemap/44_cog_stac.ipynb
      - geemap/45_cog_mosaic.ipynb
      - geemap/46_local_rf_training.ipynb
      - geemap/47_image_thumbnails.ipynb
      - geemap/48_folium_legend.ipynb
      - geemap/49_colorbar.ipynb
      - geemap/50_cartoee_quickstart.ipynb
      - geemap/51_cartoee_projections.ipynb
      - geemap/52_cartoee_gif.ipynb
      - geemap/53_layer_vis.ipynb
      - geemap/54_vector_vis.ipynb
      - geemap/55_raster_vis.ipynb
      - geemap/56_local_data.ipynb
      - geemap/57_cartoee_blend.ipynb
      - geemap/58_add_vector.ipynb
      - geemap/59_whitebox.ipynb
      - geemap/60_colormaps.ipynb
      - geemap/61_cartoee_scalebar.ipynb
      - geemap/62_time_slider.ipynb
      - geemap/63_charts.ipynb
      - geemap/64_data_catalog.ipynb
      - geemap/65_vector_styling.ipynb
      - geemap/66_cartoee_legend.ipynb
      - geemap/67_training_samples.ipynb
      - geemap/68_netcdf_to_ee.ipynb
      - geemap/69_cartoee_vector.ipynb
      - geemap/70_linked_maps.ipynb
      - geemap/71_timelapse.ipynb
      - geemap/72_time_slider_gui.ipynb
      - geemap/73_transect.ipynb
      - geemap/74_csv_to_points.ipynb
      - geemap/75_sankee.ipynb
      - geemap/76_osm_to_ee.ipynb
      - geemap/77_planet_imagery.ipynb
      - geemap/78_ts_inspector.ipynb
      - geemap/79_chart_histogram.ipynb
      - geemap/80_point_layer.ipynb
      - geemap/81_goes_timelapse.ipynb
      - geemap/82_contours.ipynb
      - geemap/83_local_tile.ipynb
      - geemap/84_openstreetmap.ipynb
      - geemap/85_postgis.ipynb
      - geemap/86_image_overlay.ipynb
      - geemap/87_add_points_from_xy.ipynb
      - geemap/88_circle_markers.ipynb
      - geemap/89_add_labels.ipynb
      - geemap/90_naip_timelapse.ipynb
      - geemap/91_planetary_computer.ipynb
      - geemap/92_plotly.ipynb
      - geemap/93_cog_inspector.ipynb
      - geemap/94_heremap.ipynb
      - geemap/95_create_cog.ipynb
      - geemap/96_image_chips.ipynb
      - geemap/97_join_table.ipynb
      - geemap/98_timelapse_fading.ipynb
      - geemap/99_landsat_9.ipynb
      - geemap/100_numpy_to_cog.ipynb
      - geemap/101_lidar.ipynb
      - geemap/102_blend_hillshade.ipynb
      - geemap/103_split_control.ipynb
  - Leafmap:
      - leafmap/01_leafmap_intro.ipynb
      - leafmap/02_using_basemaps.ipynb
      - leafmap/03_cog_stac.ipynb
      - leafmap/04_cog_mosaic.ipynb
      - leafmap/05_load_raster.ipynb
      - leafmap/06_legend.ipynb
      - leafmap/07_colorbar.ipynb
      - leafmap/08_whitebox.ipynb
      - leafmap/09_csv_to_points.ipynb
      - leafmap/10_add_vector.ipynb
      - leafmap/11_linked_maps.ipynb
      - leafmap/12_split_map.ipynb
      - leafmap/13_geopandas.ipynb
      - leafmap/14_postgis.ipynb
      - leafmap/15_openstreetmap.ipynb
      - leafmap/16_heremap.ipynb
      - leafmap/17_vector_tile_layer.ipynb
      - leafmap/18_point_layer.ipynb
      - leafmap/19_map_to_html.ipynb
      - leafmap/20_planet_imagery.ipynb
      - leafmap/21_ts_inspector.ipynb
      - leafmap/22_time_slider.ipynb
      - leafmap/23_colormaps.ipynb
      - leafmap/24_heatmap.ipynb
      - leafmap/25_map_title.ipynb
      - leafmap/26_kepler_gl.ipynb
      - leafmap/27_basemap_gallery.ipynb
      - leafmap/28_publish_map.ipynb
      - leafmap/29_pydeck.ipynb
      - leafmap/30_census_data.ipynb
      - leafmap/31_search_basemaps.ipynb
      - leafmap/32_local_tile.ipynb
      - leafmap/33_image_overlay.ipynb
      - leafmap/34_add_points_from_xy.ipynb
      - leafmap/35_circle_markers.ipynb
      - leafmap/36_add_labels.ipynb
      - leafmap/37_planetary_computer.ipynb
      - leafmap/38_plotly.ipynb
      - leafmap/39_inspector_tool.ipynb
      - leafmap/40_plotly_gui.ipynb
      - leafmap/41_raster_gui.ipynb
      - leafmap/42_create_cog.ipynb
      - leafmap/43_search_control.ipynb
      - leafmap/44_attribute_table.ipynb
      - leafmap/45_create_vector.ipynb
      - leafmap/46_edit_vector.ipynb
      - leafmap/47_numpy_to_cog.ipynb
      - leafmap/48_lidar.ipynb
      - leafmap/49_split_control.ipynb
  - Blog: https://blog.gishub.org
  - YouTube Channel: https://www.youtube.com/c/QiushengWu
  - Report Issues: https://github.com/giswqs/geospatial-notebooks/issues
